version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build the app
          command: yarn run build

workflows:
  run-on-push:
    jobs:
      - build
