version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run: yarn build
      - run: yarn test

workflows:
  run-on-push:
    jobs:
      - build
